// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,players:12, defenders:26, state:30, baller:36, position:40, defense:54, action:70, move:76, pass:78, screen:80, before:88, after:90, middle:92, actions:96}
export const parser = LRParser.deserialize({
  version: 14,
  states: ".dQYQPOOOOQO'#Dj'#DjOOQO'#C_'#C_OOQO'#Da'#DaQYQPOOOqQPO'#C`OvQPO'#ChO{QPO'#CjO!QQPO'#DOO!VQPO'#D]OOQO-E7_-E7_O![QPO,58zO!aQPO,59SO!fQPO,59UO!kQPO,59jO!pQPO,59wO!uQPO1G.fO!}QPO1G.nO#VQPO1G.pO#eQPO1G/UO#sQPO1G/cO#{QPO'#CeOOQO7+$Q7+$QO$TQPO7+$QOOQO7+$Y7+$YO$YQPO7+$YOOQO'#Cl'#ClOOQO'#Dc'#DcO$_QPO7+$[O$mQPO'#CmO$rQPO'#CoO$wQPO'#CvOOQO7+$[7+$[O$|QPO'#DQOOQO'#DR'#DRO%RQPO7+$pO%WQPO'#DfO%cQPO7+$}OOQO7+$}7+$}O%kQPO,59PO%sQPO,59POOQO<<Gl<<GlOOQO<<Gt<<GtOOQO-E7a-E7aOOQO<<Gv<<GvO%{QPO,59XO&QQPO,59ZO&VQPO,59bO&[QPO,59lOOQO<<H[<<H[OOQO,5:Q,5:QOOQO-E7d-E7dOOQO<<Hi<<HiOOQO,59|,59|O&aQPO1G.kOOQO-E7`-E7`O&iQPO1G.sO&zQPO1G.uO'SQPO1G.|O'[QPO1G/WP'dQPO'#DbOOQO7+$_7+$_O'iQPO'#CqOOQO'#Dd'#DdO'nQPO7+$aO'vQPO7+$aO(XQPO'#CxOOQO'#De'#DeO(jQPO7+$hO(rQPO7+$hO)TQPO'#CrO)YQPO'#DVO)kQPO7+$rO'_QPO,59]OOQO-E7b-E7bO)pQPO<<G{OOQO<<G{<<G{OOQO'#Cy'#CyO'_QPO,59dO*RQPO,59dOOQO-E7c-E7cO*ZQPO<<HSOOQO<<HS<<HSO*lQPO,59^O*qQPO,59qO'_QPO,59qOOQO<<H^<<H^O*yQPO1G.wOOQOAN=gAN=gO+UQPO1G/OOOQOAN=nAN=nO+aQPO1G.xO+fQPO1G/]O+qQPO1G/]OOQO7+$c7+$cOOQO7+$j7+$jO+yQPO7+$dOOQO7+$w7+$wO,OQPO7+$wOOQO<<HO<<HOO,ZQPO<<HcOOQO'#DX'#DXOOQOAN=}AN=}",
  stateData: ",c~O!]OSPOS~OTPOUTO]UO_VOhPOsWO!QXO~OVZO~OV[O~OV]O~OV^O~OV_O~OW`O~OWaO~OWbO~OWcO~O!RdO~OTeOZfO~OTeOZhO~OZpObmOdnOkoO~OkrOvrOwrOxrO~OsWO!SvO~OYwOZXX~OZyO~OZzO~OZ|ObmOdnOkoO~OV}O~OV!OO~OV!PO~OV!QO~OZ!RO~OY!SOs!YX!S!YX~OsWO!S!UO~OT!VOZXa~OY!WOZXa~OT!YO~OW!ZO~OW![O~OW!]O~OT!VOZXi~OY!_OZaibaidaikai~OT!`OZ!cO~OT!dOZ!gO~OT!iOg!hO~OT!VO~OV!kO~OT!`OZ!mO~OY!nOZcqbcqdcqkcq~OV!pOn!oOo!oOp!oOq!oO~OT!dOZ!sO~OY!tOZjqbjqdjqkjq~Oh!uO~OV!wOn!oOo!oOp!oOq!oO~OZ!xO~OY!zOZcybcydcykcy~OT!{Og!hO~OY!|OZjybjydjykjy~OY!}O~OT#OOg!hO~OY#QOTeiZei~OY#ROTliZli~Oh#SO~OY#TOz#UOZyi~OY#TOZyi~Oi#VO~O|#XO}#XO!O#XO~OY#YOZyy~O",
  goto: "$p!_PPP!`!dPPPP!hPP!dP!dP!n!rP!rP!v!zPPP!rP#[#`PPPP#fP#n#qPPP#tP#wPPP!dPPP#z$Q$W$^$d$jPPP!dTROSTQOSQg`RiaTkblTjblT!a!Z!bQ!i!]Q!y!kS!{!p!qQ#O!vR#P!wT!e![!fQ!q!dR!v!iSQOSTtduRscRqcR!j!]R#W#UQSORYSQxeR!XxQlbR{lQ!b!ZR!l!bQ!f![R!r!fQudR!Tu",
  nodeNames: "⚠ LineComment Program TopLevel Players Identifier players = { IdentifierList , } Defenders defenders State state StateContent BallerAssignment baller PositionAssignment position PositionEntry Coordinate ( Number ) DefenseAssignment defense DefenseEntry Arrow -> ~> CurveArrow OffsetArrow ActionBlock action ActionDefinition ActionType move pass screen ActionBody : Timing before after middle ActionsBlock actions [ ]",
  maxTerm: 60,
  skippedNodes: [0,1],
  repeatNodeCount: 6,
  tokenData: "(a~RjX^!spq!sxy#hyz#m|}#r}!O#w!P!Q%k!Q![$T![!]&Y!_!`&_!c!}&d!}#O&u#P#Q&z#R#S&d#T#o&d#o#p'P#q#r'U#r#s'Z#y#z!s$f$g!s#BY#BZ!s$IS$I_!s$I|$JO!s$JT$JU!s$KV$KW!s&FU&FV!s~!xY!]~X^!spq!s#y#z!s$f$g!s#BY#BZ!s$IS$I_!s$I|$JO!s$JT$JU!s$KV$KW!s&FU&FV!s~#mOg~~#rOi~~#wOY~~#zR!Q![$T!`!a$n!}#O$s~$YQh~!O!P$`!Q![$T~$cP!Q![$f~$kPh~!Q![$f~$sOn~~$vUOY$sZ#P$s#P#Q%Y#Q;'S$s;'S;=`%e<%lO$s~%]P!`!a%`~%eOq~~%hP;=`<%l$s~%nP!P!Q%q~%vSP~OY%qZ;'S%q;'S;=`&S<%lO%q~&VP;=`<%l%q~&_Oz~~&dOV~~&iST~!Q![&d!c!}&d#R#S&d#T#o&d~&zO!R~~'PO!S~~'UOW~~'ZOZ~~'^Q!`!a'd!}#O'i~'iOo~~'lUOY'iZ#P'i#P#Q(O#Q;'S'i;'S;=`(Z<%lO'i~(RP!`!a(U~(ZOp~~(^P;=`<%l'i",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 5, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 0
})
