version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "cargo"
    directory: "cli/"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "cargo"
    directory: "core/"
    schedule:
      interval: "weekly"