[package]
name = "playbook-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
playbook_lang_core = { path = "../core" }
playbook_lang_formatter = { path = "../formatter" }
playbook_lang_linter = { path = "../linter" }
clap = { version = "4.5", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "benchmark"
harness = false